New_topic_button_icon:
  default: "handshake"
  description:
    en: Choose an icon for the button. You can use any FontAwesome 4.7 icon name like "music" or "star" without quote marks.
New_topic_button_text:
  default: "Endorse a participant"
  description:
    en: "Enter the text you want the button to use. You can also leave this empty if you want to only use an icon."
New_topic_button_title:
  default: "Grant endorsement(s) to team participants for their work during virtual-internships."
  description:
    en: "Enter the title you want the button to use. If this is left empty, the title will be the same as the button text."
endorsement_category:
  type: list
  list_type: category
  default: "399"
  description:
    en: "Category where endorsement topics will be created. NOTE: Choose only one category"
Topic_title:
  default: "Virtual-Internship 2022 Endorsements"
  description:
    en: "Enter the title you want for the post that will be created."
endorsement_badge_id:
  type: integer
  default: 138
  description:
    en: "Badge ID of endorsement"
subtitle:
  default: "Endorsements for the Virtual-Internship 2022 Sessions"
  description:
    en: "Enter the subtitle you want for the modal. Below Peer Endorsements"
description_placeholder:
  default: "Enter your description of why you would like to endorse a particular individual"
  description:
    en: "Enter the placeholder you want for the description field."
